#!/bin/sh

# Login info for raspberry pi
rasp_user="rpi"
rasp_host="raspi"

case $1 in
  off|standby)
    command="standby"
  ;;
  on)
    command="on"
  ;;
  *)
    echo "Unknown command"
    exit 0
esac

notify-send "TV $command"

# Send on/standby command through HDMI CEC
ssh "$rasp_user@$rasp_host" "echo $command 0 | cec-client -s"
